export const PLAYING = 'V-PLAYBACKS-PLAYBACKEVENT-PLAYING'
export const BUFFERING = 'V-PLAYBACKS-PLAYBACKEVENT-BUFFERING'
export const NOT_BUFFERING = 'V-PLAYBACKS-PLAYBACKEVENT-NOT_BUFFERING'
export const PAUSED = 'V-PLAYBACKS-PLAYBACKEVENT-PAUSED'
export const TIME_UPDATE = 'V-PLAYBACKS-PLAYBACKEVENT-TIME_UPDATE'
export const LOAD_METADATA = 'V-PLAYBACKS-PLAYBACKEVENT-LOAD_METADATA'
export const ENDED = 'V-PLAYBACKS-PLAYBACKEVENT-ENDED'
export const ERROR = 'V-PLAYBACKS-PLAYBACKEVENT-ERROR'
export const START_PROGRESS = 'V-PLAYBACKS-PLAYBACKEVENT-START_PROGRESS'

export default {
  PLAYING,
  BUFFERING,
  NOT_BUFFERING,
  PAUSED,
  TIME_UPDATE,
  LOAD_METADATA,
  ENDED,
  ERROR,
  START_PROGRESS
}
