export const ENABLE = 'V-DANMU-DANMU_EVENT-ENABLE'
export const DISABLE = 'V-DANMU-DANMU_EVENT-DISABLE'
export const SIGNIN = 'V-DANMU-DANMU_EVENT-SIGNIN'
export const SIGNUP = 'V-DANMU-DANMU_EVENT-SIGNUP'
export const SUBMIT = 'V-DANMU-DANMU_EVENT-SUBMIT'

export default {
  ENABLE, DISABLE, SIGNIN, SIGNUP, SUBMIT
}
